# Generated by Django 4.1.7 on 2023-04-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_art_transfer', '0004_alter_algorithmpreference_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmpreference',
            name='algorithm',
            field=models.CharField(blank=True, choices=[('Original', 'Original'), ('Histogram', 'Histogram'), ('Normalised', 'Normalised'), ('Combined', 'Combined')], max_length=10),
        ),
    ]
