# Generated by Django 4.1.7 on 2023-04-21 14:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import neural_art_transfer.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neural_art_transfer', '0006_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(null=True, upload_to='content_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), neural_art_transfer.models.validate_filetype]),
        ),
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(null=True, upload_to='style_images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), neural_art_transfer.models.validate_filetype])),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
