# Generated by Django 4.1.7 on 2023-04-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neural_art_transfer', '0007_alter_images_image_styleimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='styleimage',
            old_name='image',
            new_name='image_style',
        ),
    ]
